GP2-1398_comtrade_data_copy
uktrade/directory-api pull request #838
Opened 2021-02-19 08:55 UTC by bobmeredith

To do (delete all that do not apply):

 - [x] Change has a jira ticket that has the correct status.
 - [ ] Changelog entry added.

2021-02-23 16:31 UTC, depsiatwal commented on CHANGELOG.md
> +- GP2-1181 - 1398business risk
look like a typo here

2021-02-23 16:37 UTC, depsiatwal approved these changes
Small comment just on CL
nicely done :-)

2021-02-24 08:29 UTC, webbyfox commented on dataservices/tests/conftest.py
> +    models.InternetUsage.objects.all().delete()
I guess you need to delete all records from `ComtradeReport` here

2021-02-24 08:34 UTC, webbyfox commented on dataservices/tests/conftest.py
> +    models.InternetUsage.objects.all().delete()
similarly here `EaseOfDoingBusiness`

2021-02-24 08:51 UTC, webbyfox requested changes
minor comments

2021-02-24 08:56 UTC, bobmeredith commented on dataservices/tests/conftest.py
> +    models.InternetUsage.objects.all().delete()
Hehe - well spotted - thanks

2021-02-24 08:59 UTC, bobmeredith commented on CHANGELOG.md
> +- GP2-1181 - 1398business risk
Thanks for the spot.

2021-02-24 09:45 UTC, webbyfox approved these changes
LGTM

2021-02-24 09:48 UTC, merged