Gp2-1709-trade-barrier-integration
uktrade/directory-api pull request #869
Opened 2021-04-06 13:07 UTC by depsiatwal

- [ ] Change has a jira ticket that has the correct status.
 - [ ] Changelog entry added.

2021-04-07 07:46 UTC, depsiatwal commented
This builds a s3 query over trade barrier service. Service will most. likely leave some tweaks as we start FE integration. We pass in iso2 code to make it consistent with other services. There is a new class which reads all the counties and flattens so we can read by attributes. This prevents multiple reads to the database.

2021-04-07 08:22 UTC, webbyfox commented on requirements.in
> +django==2.2.13
Do we need to downgrade django?

2021-04-07 08:25 UTC, depsiatwal commented on requirements.in
> +django==2.2.13
opps not sure how that happened reverting back

2021-04-07 08:25 UTC, webbyfox commented on conf/settings.py
> +ROOT_DIR = ROOT_DIR = Path(__file__).parents[2]
Not sure what the use case of defining `ROOT_DIR` twice

2021-04-07 08:30 UTC, webbyfox commented on dataservices/core/aggregators.py
> +# ========================================================
I will move the comment under the class.

2021-04-07 08:31 UTC, depsiatwal commented on conf/settings.py
> +ROOT_DIR = ROOT_DIR = Path(__file__).parents[2]
probably type however don't think this is needed any more removed :-)

2021-04-07 08:32 UTC, bobmeredith commented on dataservices/core/aggregators.py
> +            letter_group = groups.get(key)
Somthing like this is shorter:
```
groups[key] = groups.get(key) or []
groups[key].add(instance)
```

2021-04-07 08:33 UTC, depsiatwal commented on dataservices/core/aggregators.py
> +# ========================================================
This is to categorise all the class interfaces and class aggregators. Hence needs to be before the definition.

2021-04-07 08:33 UTC, webbyfox commented on dataservices/core/aggregators.py
> +class Country:
Are we not able to use our existing `Country` model here?

2021-04-07 08:34 UTC, depsiatwal commented on dataservices/core/aggregators.py
> +class Country:
This is a nice class which transposes the country model. We only need to load once and can reuse throughout without incurring database hits. Useful as singleton class which never hits the database

2021-04-07 08:44 UTC, webbyfox commented on dataservices/views.py
> +    permission_classes = []
shall add at least authenticated permission here?

2021-04-07 08:46 UTC, webbyfox requested changes
Do trade barrier API has the key to use it? don't see atm. Just concern more about passing that SQL statements as filtering might be risky.

2021-04-07 08:49 UTC, depsiatwal commented on dataservices/core/aggregators.py
> +            letter_group = groups.get(key)
not actually using this so removed for now :-)

2021-04-07 08:49 UTC, depsiatwal commented on dataservices/core/aggregators.py
> +    pass
good point only used once now so merged

2021-04-07 08:51 UTC, depsiatwal commented on dataservices/views.py
> +    permission_classes = []
no need we don't use this for any of the dataservices it relies on hawk  though client-api service. 
we do need SSO_ID permission if we pulling user data for example but no user data us accessed here.

2021-04-07 08:52 UTC, depsiatwal commented
> Do trade barrier API has the key to use it? don't see atm. Just concern more about passing that SQL statements as filtering might be risky.

Trade barrier is 3rd party service and uses s3 services to allow filtering. As it's not database access I think they consider the model save quite a common pattern used by the data team.

2021-04-07 09:08 UTC, bobmeredith commented on dataservices/views.py
> +                filters['locations'].append(aggregated_data_helper.get_country(iso2).name)
So, the point of all this is that the trade_barrier_data_gateway will only accept location filters by country name? Surely it should use iso2/3 or numeric codes?

2021-04-07 10:02 UTC, depsiatwal commented on dataservices/views.py
> +                filters['locations'].append(aggregated_data_helper.get_country(iso2).name)
ahh yes i've changed to get_country_list to a cached property. 
Yeah trade barrier service only understand location name which is country name. No idea why they decided not to also store iso codes.

2021-04-07 12:31 UTC, bobmeredith commented on dataservices/views.py
> +                filters['locations'].append(aggregated_data_helper.get_country(iso2).name)
That cuts out the twice bit, but I suspect it's still less efficient than just using the country model. The aggregator will be instantiated the first time `get_country` is called and it loads all the countries from the db. It will do this on each and every request I think. Using `Countries.objects.filter(iso2__in=list_of_countries)` will do a table scan but would return far fewer rows and you could add an index on iso2.
Alternatively, maybe keep the look-up in memory or use the TTL cache that dataservices helpers uses.

2021-04-07 12:33 UTC, bobmeredith commented on conf/settings.py
> +)
Could we change the name of this?  `PUBLIC_API_GATEWAY_BASE_URI` sounds more generic than `datasets/market-barriers/versions/` would make it

2021-04-07 12:45 UTC, rafa-garcia commented on conf/settings.py
> +)
It also doesn't reflect a base URI as it contains a path

2021-04-08 08:06 UTC, bobmeredith approved these changes
LGTM 
Nicely done - I like the S3 SQL

2021-04-08 08:38 UTC, merged